/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practice14.quiz2remake;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Practice14Quiz2Remake extends javax.swing.JFrame {

    DefaultListModel<EmployeesSchedule> modelEmployeesScheduleList = new DefaultListModel<>();
    DefaultListModel<Weekday> modelWeekdayList = new DefaultListModel<>();
    /**
     * Creates new form Practice14Quiz2Remake
     */
    public Practice14Quiz2Remake() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgAddEdit = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        dlgAddEdit_IsManager = new javax.swing.JCheckBox();
        dlgAddEdit_tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dlgAddEdit_HiringDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dlgAddEdit_Department = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dlgAddEdit_lstWorkingDays = new javax.swing.JList<>();
        dlgAddEdit_btAddUpdate = new javax.swing.JButton();
        dlgAddEdit_btCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmployeesSchedule = new javax.swing.JList<>();
        lblStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        miFile = new javax.swing.JMenu();
        miFileExport = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miFileExit = new javax.swing.JMenuItem();
        miSortBy = new javax.swing.JMenu();
        miSortByName = new javax.swing.JRadioButtonMenuItem();
        miSortByHiredDate = new javax.swing.JRadioButtonMenuItem();
        miAdd = new javax.swing.JMenu();

        jLabel1.setText("Name:");

        dlgAddEdit_IsManager.setText("Is Manager");

        jLabel2.setText("Hiring date:");

        jLabel3.setText("Department:");

        jLabel4.setText("Working days:");

        dlgAddEdit_lstWorkingDays.setModel(modelWeekdayList);
        jScrollPane2.setViewportView(dlgAddEdit_lstWorkingDays);

        dlgAddEdit_btAddUpdate.setText("Add/Update");

        dlgAddEdit_btCancel.setText("Cancel");

        javax.swing.GroupLayout dlgAddEditLayout = new javax.swing.GroupLayout(dlgAddEdit.getContentPane());
        dlgAddEdit.getContentPane().setLayout(dlgAddEditLayout);
        dlgAddEditLayout.setHorizontalGroup(
            dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlgAddEditLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dlgAddEdit_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlgAddEditLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dlgAddEdit_IsManager)
                            .addComponent(dlgAddEdit_HiringDate)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlgAddEditLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dlgAddEdit_Department))
                    .addGroup(dlgAddEditLayout.createSequentialGroup()
                        .addComponent(dlgAddEdit_btCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(dlgAddEdit_btAddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAddEditLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 109, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        dlgAddEditLayout.setVerticalGroup(
            dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dlgAddEdit_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAddEditLayout.createSequentialGroup()
                        .addComponent(dlgAddEdit_IsManager)
                        .addGap(7, 7, 7)
                        .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(dlgAddEdit_HiringDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dlgAddEdit_Department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlgAddEdit_btAddUpdate)
                            .addComponent(dlgAddEdit_btCancel)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstEmployeesSchedule.setModel(modelEmployeesScheduleList);
        jScrollPane1.setViewportView(lstEmployeesSchedule);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lblStatus.setText("Employees working today: Jerry, Ginny, Tom");
        getContentPane().add(lblStatus, java.awt.BorderLayout.PAGE_END);

        miFile.setText("File");

        miFileExport.setText("Export to *.csv...");
        miFile.add(miFileExport);
        miFile.add(jSeparator1);

        miFileExit.setText("Exit");
        miFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFileExitActionPerformed(evt);
            }
        });
        miFile.add(miFileExit);

        jMenuBar1.add(miFile);

        miSortBy.setText("Sort by");

        miSortByName.setSelected(true);
        miSortByName.setText("Name");
        miSortBy.add(miSortByName);

        miSortByHiredDate.setSelected(true);
        miSortByHiredDate.setText("Hired date");
        miSortBy.add(miSortByHiredDate);

        jMenuBar1.add(miSortBy);

        miAdd.setText("Add");
        miAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddActionPerformed(evt);
            }
        });
        jMenuBar1.add(miAdd);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddActionPerformed
        dlgAddEdit.setVisible(true);
    }//GEN-LAST:event_miAddActionPerformed

    private void miFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFileExitActionPerformed
        if(modelEmployeesScheduleList.isEmpty())
        {
            dispose();
        }        
        try(PrintWriter printWriter = new PrintWriter(new FileWriter (new File("employees.txt"), true)))
        {        
        for(int i=0; i < modelEmployeesScheduleList.size(); i++)
        {
            printWriter.println(modelEmployeesScheduleList.getElementAt(i));
        }
        dispose();        
       }
       catch(IOException ex)
       {
           JOptionPane.showMessageDialog(this, "Error writing to file", "Error",
                    JOptionPane.INFORMATION_MESSAGE);
           dispose();
       }
    }//GEN-LAST:event_miFileExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practice14Quiz2Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practice14Quiz2Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practice14Quiz2Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practice14Quiz2Remake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practice14Quiz2Remake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlgAddEdit;
    private javax.swing.JTextField dlgAddEdit_Department;
    private javax.swing.JTextField dlgAddEdit_HiringDate;
    private javax.swing.JCheckBox dlgAddEdit_IsManager;
    private javax.swing.JButton dlgAddEdit_btAddUpdate;
    private javax.swing.JButton dlgAddEdit_btCancel;
    private javax.swing.JList<Weekday> dlgAddEdit_lstWorkingDays;
    private javax.swing.JTextField dlgAddEdit_tfName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JList<EmployeesSchedule> lstEmployeesSchedule;
    private javax.swing.JMenu miAdd;
    private javax.swing.JMenu miFile;
    private javax.swing.JMenuItem miFileExit;
    private javax.swing.JMenuItem miFileExport;
    private javax.swing.JMenu miSortBy;
    private javax.swing.JRadioButtonMenuItem miSortByHiredDate;
    private javax.swing.JRadioButtonMenuItem miSortByName;
    // End of variables declaration//GEN-END:variables
}
