/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day01homework;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Day01Homework extends javax.swing.JFrame {

    /**
     * Creates new form Day01Homework
     */
    public Day01Homework() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblPets = new javax.swing.JLabel();
        lblContinent = new javax.swing.JLabel();
        lblPreferredTemp = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        rbAgeBelow18 = new javax.swing.JRadioButton();
        rbAge18to65 = new javax.swing.JRadioButton();
        rbAgeOver65 = new javax.swing.JRadioButton();
        cbPetsCats = new javax.swing.JCheckBox();
        cbPetsDogs = new javax.swing.JCheckBox();
        cbPetsParrots = new javax.swing.JCheckBox();
        comboContinent = new javax.swing.JComboBox<>();
        sliderTempCelcius = new javax.swing.JSlider();
        btRegisterMe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("All Inputs Exercice");

        lblName.setText("Name:");

        lblAge.setText("Age:");

        lblPets.setText("Pets:");

        lblContinent.setText("Continent of residence:");

        lblPreferredTemp.setText("Preferred temp (C):");

        buttonGroup1.add(rbAgeBelow18);
        rbAgeBelow18.setSelected(true);
        rbAgeBelow18.setText("Below 18");

        buttonGroup1.add(rbAge18to65);
        rbAge18to65.setText("18 to 65");

        buttonGroup1.add(rbAgeOver65);
        rbAgeOver65.setText("Over 65");

        cbPetsCats.setText("Cats");

        cbPetsDogs.setText("Dogs");

        cbPetsParrots.setText("Parrots");

        comboContinent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "America", "Europe", "Asia", "Oceania", "Africa" }));

        sliderTempCelcius.setMajorTickSpacing(5);
        sliderTempCelcius.setMaximum(35);
        sliderTempCelcius.setMinimum(15);
        sliderTempCelcius.setMinorTickSpacing(1);
        sliderTempCelcius.setPaintLabels(true);
        sliderTempCelcius.setPaintTicks(true);
        sliderTempCelcius.setSnapToTicks(true);

        btRegisterMe.setText("Register Me");
        btRegisterMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterMeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContinent)
                    .addComponent(lblPreferredTemp)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge)
                            .addComponent(lblPets))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfName)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sliderTempCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbAgeBelow18)
                                        .addComponent(cbPetsCats)
                                        .addComponent(comboContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbAge18to65)
                                        .addComponent(cbPetsDogs))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbPetsParrots)
                                        .addComponent(rbAgeOver65, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btRegisterMe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(rbAgeBelow18)
                    .addComponent(rbAge18to65)
                    .addComponent(rbAgeOver65))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPets)
                    .addComponent(cbPetsCats)
                    .addComponent(cbPetsDogs)
                    .addComponent(cbPetsParrots))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContinent)
                    .addComponent(comboContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPreferredTemp)
                    .addComponent(sliderTempCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btRegisterMe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btRegisterMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterMeActionPerformed
        String name = tfName.getText();
        if (name.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Name must not be empty", "Input error",
                    JOptionPane.ERROR_MESSAGE); // the second "" is the window title
        }
        
        String age = "";
        if (rbAgeBelow18.isSelected())
        {
            age = "below18";
        }
        else if (rbAge18to65.isSelected())
        {
            age = "18to65";
        }
        else if (rbAgeOver65.isSelected())
        {
            age = "Over65";
        }
        else
        { // should never happen, internal error
            JOptionPane.showMessageDialog(this, "Unable to find selected radio button", "Internal error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        ArrayList <String> petsList = new ArrayList<>();
        if (cbPetsCats.isSelected())
        {
            petsList.add("cats");
        }
        if (cbPetsDogs.isSelected())
        {
            petsList.add("dogs");
        }
        if (cbPetsParrots.isSelected())
        {
            petsList.add("parrots");
        }
        
        String pets = String.join(", ", petsList); // To grab the array and turn into a String
        // with comma and space in between the elements
        
        String continent = comboContinent.getSelectedItem().toString();
        int prefTempC = sliderTempCelcius.getValue();
        String data = String.format("%s;%s;%s;%s;%d", name, age, pets, continent, prefTempC);
        
        //System.out.println(data);
        
        try (PrintWriter fileOutput = new PrintWriter(new FileWriter(new File("output.txt"), true)))        
        {
                fileOutput.println(data);
                JOptionPane.showMessageDialog(this, "Data written", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
        } 
        catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this, "Error writing to file:\n" + ex.getMessage(), "File access error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btRegisterMeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day01Homework.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day01Homework.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day01Homework.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day01Homework.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day01Homework().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegisterMe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbPetsCats;
    private javax.swing.JCheckBox cbPetsDogs;
    private javax.swing.JCheckBox cbPetsParrots;
    private javax.swing.JComboBox<String> comboContinent;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblContinent;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPets;
    private javax.swing.JLabel lblPreferredTemp;
    private javax.swing.JRadioButton rbAge18to65;
    private javax.swing.JRadioButton rbAgeBelow18;
    private javax.swing.JRadioButton rbAgeOver65;
    private javax.swing.JSlider sliderTempCelcius;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
