/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practice1;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Practice1 extends javax.swing.JFrame {

    /**
     * Creates new form Practice1
     */
    public Practice1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfFirstName = new javax.swing.JTextField();
        tfDisplayResult = new javax.swing.JTextField();
        btDisplayName = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sliderAge = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        comboColours = new javax.swing.JComboBox<>();
        tfDisplayAge = new javax.swing.JTextField();
        tfLeftToDisplay = new javax.swing.JTextField();
        tfRightToDisplay = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDisplayInfo = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        tfDate = new javax.swing.JTextField();
        btGetDate = new javax.swing.JButton();
        tfDisplayDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First name:");

        tfFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFirstNameActionPerformed(evt);
            }
        });

        tfDisplayResult.setEditable(false);

        btDisplayName.setText("Display Name");
        btDisplayName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDisplayNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Last name:");

        jLabel3.setText("Age:");

        sliderAge.setMajorTickSpacing(10);
        sliderAge.setMaximum(65);
        sliderAge.setMinimum(15);
        sliderAge.setMinorTickSpacing(5);
        sliderAge.setPaintLabels(true);
        sliderAge.setPaintTicks(true);
        sliderAge.setSnapToTicks(true);
        sliderAge.setValue(15);
        sliderAge.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAgeStateChanged(evt);
            }
        });

        jLabel4.setText("Favourite colour:");

        comboColours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pick a colour...", "Yellow", "Pink", "Red", "Black", "Blue", "White", "Green" }));

        tfDisplayAge.setEditable(false);

        tfLeftToDisplay.setEditable(false);

        taDisplayInfo.setColumns(20);
        taDisplayInfo.setRows(5);
        jScrollPane1.setViewportView(taDisplayInfo);

        jLabel5.setText("Date:");

        btGetDate.setText("Get date");
        btGetDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGetDateActionPerformed(evt);
            }
        });

        tfDisplayDate.setEditable(false);
        tfDisplayDate.setText("dd/MM/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tfDisplayAge, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(sliderAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btDisplayName))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfDisplayResult, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboColours, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(tfLeftToDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfRightToDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfDate)
                                        .addComponent(btGetDate, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                    .addGap(54, 54, 54))
                                .addComponent(tfDisplayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDisplayAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sliderAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboColours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLeftToDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRightToDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfDisplayResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDisplayName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGetDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDisplayDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearResults()
    {
        tfFirstName.setText("");
        tfLastName.setText("");
        tfDisplayResult.setText("");
    }
    
    private void btDisplayNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDisplayNameActionPerformed
        
        String firstName = tfFirstName.getText();
        if(!firstName.matches("[ a-zA-Z]{1,20}"))
        {
            JOptionPane.showMessageDialog(this, "This name format is not valid.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String lastName = tfLastName.getText();
        if(!lastName.matches("[ a-zA-Z]{1,20}"))
        {
            JOptionPane.showMessageDialog(this, "This name format is not valid.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int age = sliderAge.getValue();
        
        String colour = (String)comboColours.getSelectedItem();
        if(comboColours.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(this, "It seems you forgot to pick a colour.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return; // The return here means that the program won't keep running. 
        }
        
        tfLeftToDisplay.setText(tfRightToDisplay.getText() + ", " + sliderAge.getValue());
        
        tfDisplayResult.setText(tfFirstName.getText() + " " + tfLastName.getText() + ", " + age + ", " + colour);
        String fullName = tfFirstName.getText() + " " + tfLastName.getText();
        
        int dialogButton = JOptionPane.showConfirmDialog(this, fullName + ",\n" + "would you like to clear inputs?", "Warning",
                    JOptionPane.YES_NO_OPTION);
        if(dialogButton == JOptionPane.YES_OPTION)
        {
            clearResults();
        }
        
        
        // taDisplayInfo.setText(tfFirstName.getText() + "," + tfLastName.getText() + "," + age + "," + colour);
        
        // append won't delete the previous information, but keep adding instead:
        taDisplayInfo.append(tfFirstName.getText() + "," + tfLastName.getText() + "," + age + "," + colour+"\n");
        
        
        /*
        if(dialogButton == JOptionPane.YES_OPTION) {
        System.exit(0);}else {remove(dialogButton);}
        */
    }//GEN-LAST:event_btDisplayNameActionPerformed

    private void tfFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFirstNameActionPerformed

    private void sliderAgeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAgeStateChanged
    tfDisplayAge.setText(sliderAge.getValue() + ""); // +"" is to make it accept the int as a String
    
    /*
    Another way of doing the same:
    
    int age = sliderAge.getValue();
    tfDisplayAge.setText(age+"");
    */
    
    }//GEN-LAST:event_sliderAgeStateChanged

    private void btGetDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGetDateActionPerformed
        
        /* this was a test...
        String price = "5.000";
        double pr = Double.parseDouble(price);
        System.out.println(pr);
        */
        
        //Date date = null; // created a variable called date of the type Date (Same as String, int, etc., but of type Date)
        
        // we need to parse it (basically to change its type)
        // next step is to create format:
        Date date = new Date();
        SimpleDateFormat correctFormat = new SimpleDateFormat("dd/MM/yyyy");
        String strDate = correctFormat.format(date);                  
        try
        {
          date = correctFormat.parse(tfDate.getText());
          System.out.println(strDate);
        }
        catch(ParseException ex)
        {
            JOptionPane.showMessageDialog(this, "Wrong date format. Please mind the following format: dd/mm/yyyy", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        //String dateStr ="";
        //tfDisplayDate.setText(strDate.format("%tD", date)); --> This will go to another format
        tfDisplayDate.setText(correctFormat.format(date));
     //   tfDisplayDate.setText(date+"");
        
    }//GEN-LAST:event_btGetDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practice1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDisplayName;
    private javax.swing.JButton btGetDate;
    private javax.swing.JComboBox<String> comboColours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider sliderAge;
    private javax.swing.JTextArea taDisplayInfo;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfDisplayAge;
    private javax.swing.JTextField tfDisplayDate;
    private javax.swing.JTextField tfDisplayResult;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JTextField tfLeftToDisplay;
    private javax.swing.JTextField tfRightToDisplay;
    // End of variables declaration//GEN-END:variables
}
