/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practice13.bigwork;

import java.awt.event.MouseEvent;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.DefaultListModel;
import static practice13.bigwork.Birthday.dateFormat;


public class Practice13BigWork extends javax.swing.JFrame {
    

    DefaultListModel<String> modelBirthdayList = new DefaultListModel<>();
    DefaultListModel<String> modelDialogBirthdayList = new DefaultListModel<>();
    
    public Practice13BigWork() {
        initComponents();
        
        //Months go from 0 to 11
        Date date = new GregorianCalendar(1985, 10, 21).getTime(); // ATTENTION: MONTH 11 = December 

        System.out.println(new Birthday("Bab", date).getDaysTillBday());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        dlgAddEdit = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        dlgAddEdit_tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dlgAddEdit_tfBirthday = new javax.swing.JTextField();
        dlgAddEdit_btCancel = new javax.swing.JButton();
        dlgAddEdit_btSave = new javax.swing.JButton();
        dlgAddEdit_dpBirthday = new org.jdatepicker.JDatePicker();
        dlgStats = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dlgStats_tfTotalFriends = new javax.swing.JTextField();
        dlgStats_tfComingBdays = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dlgStats_lstBirthdays = new javax.swing.JList<>();
        dlgStats_btDismiss = new javax.swing.JButton();
        popupMenu = new javax.swing.JPopupMenu();
        popupMenuEdit = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        popupMenuDelete = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstBirthday = new javax.swing.JList<>();
        lblStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        miFile = new javax.swing.JMenu();
        miFileExport = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miFileExit = new javax.swing.JMenuItem();
        miSortBy = new javax.swing.JMenu();
        miSortByRbName = new javax.swing.JRadioButtonMenuItem();
        miSortByRbBirthday = new javax.swing.JRadioButtonMenuItem();
        miSortByRbDaysUntilBday = new javax.swing.JRadioButtonMenuItem();
        miAdd = new javax.swing.JMenu();
        miStatistics = new javax.swing.JMenu();

        dlgAddEdit.setModal(true);

        jLabel1.setText("Name:");

        jLabel2.setText("Birthday:");

        dlgAddEdit_btCancel.setText("Cancel");
        dlgAddEdit_btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgAddEdit_btCancelActionPerformed(evt);
            }
        });

        dlgAddEdit_btSave.setText("Save");
        dlgAddEdit_btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgAddEdit_btSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgAddEditLayout = new javax.swing.GroupLayout(dlgAddEdit.getContentPane());
        dlgAddEdit.getContentPane().setLayout(dlgAddEditLayout);
        dlgAddEditLayout.setHorizontalGroup(
            dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAddEditLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dlgAddEdit_tfName))
                    .addGroup(dlgAddEditLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgAddEditLayout.createSequentialGroup()
                                .addComponent(dlgAddEdit_dpBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(dlgAddEditLayout.createSequentialGroup()
                                .addComponent(dlgAddEdit_tfBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dlgAddEdit_btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dlgAddEdit_btSave, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        dlgAddEditLayout.setVerticalGroup(
            dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dlgAddEdit_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dlgAddEdit_tfBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlgAddEdit_btCancel)
                    .addComponent(dlgAddEdit_btSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dlgAddEdit_dpBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgStats.setModal(true);

        jLabel3.setText("Total number of friends:");

        jLabel4.setText("Coming birthdays in the next 7 days:");

        jLabel5.setText("Birthdays per month:");

        dlgStats_lstBirthdays.setModel(modelDialogBirthdayList);
        dlgStats_lstBirthdays.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(dlgStats_lstBirthdays);

        dlgStats_btDismiss.setText("Dismiss");

        javax.swing.GroupLayout dlgStatsLayout = new javax.swing.GroupLayout(dlgStats.getContentPane());
        dlgStats.getContentPane().setLayout(dlgStatsLayout);
        dlgStatsLayout.setHorizontalGroup(
            dlgStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(dlgStatsLayout.createSequentialGroup()
                .addGroup(dlgStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgStatsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlgStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dlgStatsLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dlgStats_tfTotalFriends))
                            .addGroup(dlgStatsLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dlgStats_tfComingBdays, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(dlgStatsLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel5))
                    .addGroup(dlgStatsLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(dlgStats_btDismiss)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgStatsLayout.setVerticalGroup(
            dlgStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dlgStats_tfTotalFriends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dlgStats_tfComingBdays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dlgStats_btDismiss)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        popupMenuEdit.setText("Edit");
        popupMenuEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popupMenuEditMouseClicked(evt);
            }
        });
        popupMenuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupMenuEditActionPerformed(evt);
            }
        });
        popupMenu.add(popupMenuEdit);
        popupMenu.add(jSeparator2);

        popupMenuDelete.setText("Delete");
        popupMenuDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popupMenuDeleteMouseClicked(evt);
            }
        });
        popupMenuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupMenuDeleteActionPerformed(evt);
            }
        });
        popupMenu.add(popupMenuDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Birthdays");

        lstBirthday.setModel(modelBirthdayList);
        lstBirthday.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstBirthday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstBirthdayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstBirthday);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lblStatus.setText("Status");
        getContentPane().add(lblStatus, java.awt.BorderLayout.PAGE_END);

        miFile.setText("File");

        miFileExport.setText("Export to *.csv...");
        miFile.add(miFileExport);
        miFile.add(jSeparator1);

        miFileExit.setText("Exit");
        miFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFileExitActionPerformed(evt);
            }
        });
        miFile.add(miFileExit);

        jMenuBar1.add(miFile);

        miSortBy.setText("Sort by");

        buttonGroup2.add(miSortByRbName);
        miSortByRbName.setSelected(true);
        miSortByRbName.setText("Name");
        miSortBy.add(miSortByRbName);

        buttonGroup2.add(miSortByRbBirthday);
        miSortByRbBirthday.setText("Birthday");
        miSortBy.add(miSortByRbBirthday);

        buttonGroup2.add(miSortByRbDaysUntilBday);
        miSortByRbDaysUntilBday.setText("Days until birthday");
        miSortBy.add(miSortByRbDaysUntilBday);

        jMenuBar1.add(miSortBy);

        miAdd.setText("Add");
        miAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miAddMouseClicked(evt);
            }
        });
        miAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddActionPerformed(evt);
            }
        });
        jMenuBar1.add(miAdd);

        miStatistics.setText("Statistics");
        miStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStatisticsActionPerformed(evt);
            }
        });
        jMenuBar1.add(miStatistics);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddActionPerformed
        dlgAddEdit.setVisible(true);
    }//GEN-LAST:event_miAddActionPerformed

    private void miStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStatisticsActionPerformed
        dlgStats.setVisible(true);
    }//GEN-LAST:event_miStatisticsActionPerformed

    private void miFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFileExitActionPerformed
        dispose();
    }//GEN-LAST:event_miFileExitActionPerformed

    // This variable does all the trick if I'm adding or if I'm editing
    // This information should be available when the save button is pressed
    int currentlyEditedItemIndex = -1; // -1 means we're adding, not editing
    
    private void miAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miAddMouseClicked
        //display "Add friend" while clicking
        dlgAddEdit_btSave.setText("Add");        
        //adding instead of editing
        currentlyEditedItemIndex = -1;        
        //cleanup the dialog before showing it
        dlgAddEdit_tfName.setText("");
        
        // SHOW THE DIALOG
        //to resize window to fit components
        dlgAddEdit.pack();
        //set location relative to parent, so dialog shows in the center of parent(JFrame)
        dlgAddEdit.setLocationRelativeTo(this);
        //set dialog visible
        dlgAddEdit.setVisible(true);
    }//GEN-LAST:event_miAddMouseClicked

    private void dlgAddEdit_btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgAddEdit_btCancelActionPerformed
        //when "Cancel" button is pressed to make dialog not visible
        dlgAddEdit.setVisible(false);
    }//GEN-LAST:event_dlgAddEdit_btCancelActionPerformed
        
    private void dlgAddEdit_btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgAddEdit_btSaveActionPerformed
        String name = dlgAddEdit_tfName.getText();
        String date = dlgAddEdit_tfBirthday.getText();//get value from datepicker and convert to date
        
        //dlgAddEdit_dpBirthday.getFormattedTextField();
        
        if(currentlyEditedItemIndex == -1)
        {
            //add name to model
            //modelBirthdayList.addElement(new Birthday("Bab", date).getDaysTillBday());
        // (name + " born " + " birthday in " + new Birthday(""));
            // new Birthday("Bab", date).getDaysTillBday()
        }
        else
        {
            modelBirthdayList.set(currentlyEditedItemIndex, name);
        }        
        //hide dialog window
        dlgAddEdit.setVisible(false);
        
    }//GEN-LAST:event_dlgAddEdit_btSaveActionPerformed

    private void lstBirthdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstBirthdayMouseClicked
        if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) // Button1 = left button
        {
            int index = lstBirthday.getSelectedIndex();
            if(index == -1) // if no selection
            {
                return; 
            }
            //set the text to "Update"
            dlgAddEdit_btSave.setText("Update friend");
           
            //cleanup the dialog before showing it
            currentlyEditedItemIndex = index;
            dlgAddEdit_tfName.setText(modelBirthdayList.get(index));
            
            // SHOW THE DIALOG
            //to resize window to fit components
            dlgAddEdit.pack();
            //set location relative to parent, so dialog shows in the center of parent(JFrame)
            dlgAddEdit.setLocationRelativeTo(this);
            //set dialog visible
            dlgAddEdit.setVisible(true); 
        }
        
        //to check if mouse was clicked 2 times and only right button was clicked
        if(evt.getButton() == MouseEvent.BUTTON3) // button3 = right button
       {
           int index = lstBirthday.getSelectedIndex();
           if(index == -1)
           {
               return; //no selection
           }
           //show pop up
            lstBirthday.setSelectedIndex(lstBirthday.locationToIndex(evt.getPoint())); //select the item
            popupMenu.show(lstBirthday, evt.getX(), evt.getY()); //and show the menu         
       }
        
    }//GEN-LAST:event_lstBirthdayMouseClicked

    private void popupMenuEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupMenuEditMouseClicked
        // sb action performed instead
    }//GEN-LAST:event_popupMenuEditMouseClicked

    private void popupMenuDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupMenuDeleteMouseClicked
        // sb action performed instead
    }//GEN-LAST:event_popupMenuDeleteMouseClicked

    private void popupMenuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupMenuEditActionPerformed
        int index = lstBirthday.getSelectedIndex();
        if(index == -1) // if no selection
        {
            return; 
        }
        //set the text to "Update"
        dlgAddEdit_btSave.setText("Update friend");
           
        //cleanup the dialog before showing it
        currentlyEditedItemIndex = index;
        dlgAddEdit_tfName.setText(modelBirthdayList.get(index));
            
        // SHOW THE DIALOG
        //to resize window to fit components
        dlgAddEdit.pack();
        //set location relative to parent, so dialog shows in the center of parent(JFrame)
        dlgAddEdit.setLocationRelativeTo(this);
        //set dialog visible
        dlgAddEdit.setVisible(true); 
    }//GEN-LAST:event_popupMenuEditActionPerformed

    private void popupMenuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupMenuDeleteActionPerformed
        modelBirthdayList.removeElementAt(lstBirthday.getSelectedIndex());
    }//GEN-LAST:event_popupMenuDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practice13BigWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practice13BigWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practice13BigWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practice13BigWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practice13BigWork().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JDialog dlgAddEdit;
    private javax.swing.JButton dlgAddEdit_btCancel;
    private javax.swing.JButton dlgAddEdit_btSave;
    private org.jdatepicker.JDatePicker dlgAddEdit_dpBirthday;
    private javax.swing.JTextField dlgAddEdit_tfBirthday;
    private javax.swing.JTextField dlgAddEdit_tfName;
    private javax.swing.JDialog dlgStats;
    private javax.swing.JButton dlgStats_btDismiss;
    private javax.swing.JList<String> dlgStats_lstBirthdays;
    private javax.swing.JTextField dlgStats_tfComingBdays;
    private javax.swing.JTextField dlgStats_tfTotalFriends;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JList<String> lstBirthday;
    private javax.swing.JMenu miAdd;
    private javax.swing.JMenu miFile;
    private javax.swing.JMenuItem miFileExit;
    private javax.swing.JMenuItem miFileExport;
    private javax.swing.JMenu miSortBy;
    private javax.swing.JRadioButtonMenuItem miSortByRbBirthday;
    private javax.swing.JRadioButtonMenuItem miSortByRbDaysUntilBday;
    private javax.swing.JRadioButtonMenuItem miSortByRbName;
    private javax.swing.JMenu miStatistics;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JMenuItem popupMenuDelete;
    private javax.swing.JMenuItem popupMenuEdit;
    // End of variables declaration//GEN-END:variables
}
