/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practice2;

import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Practice2 extends javax.swing.JFrame {

    /**
     * Creates new form Practice2
     */
    public Practice2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        rbBelow18 = new javax.swing.JRadioButton();
        rb18to65 = new javax.swing.JRadioButton();
        rbOver65 = new javax.swing.JRadioButton();
        cbPetsCats = new javax.swing.JCheckBox();
        cbPetsDogs = new javax.swing.JCheckBox();
        cbPetsOther = new javax.swing.JCheckBox();
        sliderTemp = new javax.swing.JSlider();
        comboContinents = new javax.swing.JComboBox<>();
        btRegisterMe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        tfTempDisplay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("All Inputs");

        jLabel1.setText("Name:");

        jLabel2.setText("Age:");

        jLabel3.setText("Pets:");

        jLabel4.setText("Continent:");

        jLabel5.setText("Preferred Temperature (in °C):");

        buttonGroup1.add(rbBelow18);
        rbBelow18.setSelected(true);
        rbBelow18.setText("Below 18");

        buttonGroup1.add(rb18to65);
        rb18to65.setText("18 to 65");

        buttonGroup1.add(rbOver65);
        rbOver65.setText("Over 65");

        cbPetsCats.setText("Cat(s)");

        cbPetsDogs.setText("Dog(s)");

        cbPetsOther.setText("Other");

        sliderTemp.setMajorTickSpacing(10);
        sliderTemp.setMaximum(35);
        sliderTemp.setMinimum(15);
        sliderTemp.setMinorTickSpacing(1);
        sliderTemp.setPaintLabels(true);
        sliderTemp.setPaintTicks(true);
        sliderTemp.setSnapToTicks(true);
        sliderTemp.setValue(25);
        sliderTemp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTempStateChanged(evt);
            }
        });

        comboContinents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "America", "Europe", "Asia", "Africa", "Oceania" }));

        btRegisterMe.setText("Register Me!");
        btRegisterMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterMeActionPerformed(evt);
            }
        });

        taOutput.setEditable(false);
        taOutput.setColumns(20);
        taOutput.setRows(5);
        jScrollPane1.setViewportView(taOutput);

        tfTempDisplay.setBackground(new java.awt.Color(102, 204, 255));
        tfTempDisplay.setText("25");
        tfTempDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTempDisplayActionPerformed(evt);
            }
        });

        jLabel6.setText("Or type here:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbBelow18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbPetsCats)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb18to65)
                                            .addComponent(cbPetsDogs))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbPetsOther)
                                            .addComponent(rbOver65)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfTempDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sliderTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboContinents, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(btRegisterMe)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbBelow18)
                    .addComponent(rb18to65)
                    .addComponent(rbOver65))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPetsCats)
                    .addComponent(cbPetsDogs)
                    .addComponent(cbPetsOther))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboContinents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTempDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(sliderTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btRegisterMe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btRegisterMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterMeActionPerformed
        String name = tfName.getText();
        if(!name.matches("[a-zA-Z- ]{1,50}"))
        {
            JOptionPane.showMessageDialog(this, "The name must contain (A to Z) letters and between 1 and 50 characters.", 
                    "Input error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        
        String age = "";
        if(rbBelow18.isSelected())
        {
            age = "Below 18";
        }
        else if(rb18to65.isSelected())
        {
            age = "18 to 65";
        }
        else if(rbOver65.isSelected())
        {
            age = "Over 65";
        }
        else
        { // should never happen, internal error
            JOptionPane.showMessageDialog(this, "Unable to find selected radio button.", "Internal error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        ArrayList <String> petsList = new ArrayList<>();        
        if(cbPetsDogs.isSelected())
        {
            petsList.add("dogs");
        }
        if(cbPetsCats.isSelected())
        {
            petsList.add("cats");
        }
        if(cbPetsOther.isSelected())
        {
            petsList.add("other");
        }
        String pets = String.join(", ", petsList); // To grab the array and turn into a String
        // with comma and space in between the elements
        
        // Combo is an object, so it needs toString()
        String continent = comboContinents.getSelectedItem().toString();
        
        int prefTemp = sliderTemp.getValue();
        
        taOutput.append(name + ", " + age + ", " + pets + ", " + continent + ", " + prefTemp + " °C\n");
    }//GEN-LAST:event_btRegisterMeActionPerformed

    private void sliderTempStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTempStateChanged
        int prefTemp = sliderTemp.getValue();
        tfTempDisplay.setText(prefTemp + " °C");
    }//GEN-LAST:event_sliderTempStateChanged

    private void tfTempDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTempDisplayActionPerformed
        String str = tfTempDisplay.getText();
        int num = 0;
        try
        {
            num = Integer.parseInt(str);
        }
        catch(NumberFormatException ex)
        {
             JOptionPane.showMessageDialog(this, "This value is not valid, it must be a number",                   
                    "Input error", JOptionPane.ERROR_MESSAGE); // the second "" is the window title
             return;
        }
        if(num < sliderTemp.getMinimum())
        {
            num = sliderTemp.getMinimum();
        }
        if(num > sliderTemp.getMaximum())
        {
            num = sliderTemp.getMaximum();
        }
                
        sliderTemp.setValue(num);
        
      
        
            
        
    }//GEN-LAST:event_tfTempDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practice2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegisterMe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbPetsCats;
    private javax.swing.JCheckBox cbPetsDogs;
    private javax.swing.JCheckBox cbPetsOther;
    private javax.swing.JComboBox<String> comboContinents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb18to65;
    private javax.swing.JRadioButton rbBelow18;
    private javax.swing.JRadioButton rbOver65;
    private javax.swing.JSlider sliderTemp;
    private javax.swing.JTextArea taOutput;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfTempDisplay;
    // End of variables declaration//GEN-END:variables
}
