/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practice3;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Practice3 extends javax.swing.JFrame {

    /**
     * Creates new form Practice3
     */
    public Practice3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfPassportNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboContinent = new javax.swing.JComboBox<>();
        rbGenderMale = new javax.swing.JRadioButton();
        rbGenderFemale = new javax.swing.JRadioButton();
        rbGenderNotSure = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbPetsFish = new javax.swing.JCheckBox();
        cbPetsPig = new javax.swing.JCheckBox();
        cbPetsGoat = new javax.swing.JCheckBox();
        cbPetsOther = new javax.swing.JCheckBox();
        sliderHeight = new javax.swing.JSlider();
        tfDisplayHeight = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ftDateOfBirth = new javax.swing.JFormattedTextField();
        btVerifyAndAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDisplayInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Border control");

        lblName.setText("Name:");

        jLabel1.setText("Passport Number:");

        jLabel2.setText("Continent:");

        comboContinent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please choose...", "America", "Europe", "Asia", "Africa", "Oceania" }));

        buttonGroup1.add(rbGenderMale);
        rbGenderMale.setSelected(true);
        rbGenderMale.setText("Male");

        buttonGroup1.add(rbGenderFemale);
        rbGenderFemale.setText("Female");

        buttonGroup1.add(rbGenderNotSure);
        rbGenderNotSure.setText("I'm not sure");

        jLabel3.setText("Gender:");

        jLabel4.setText("Pets:");

        cbPetsFish.setText("Fish");

        cbPetsPig.setText("Pig");

        cbPetsGoat.setText("Goat");

        cbPetsOther.setText("Other");

        sliderHeight.setMajorTickSpacing(10);
        sliderHeight.setMaximum(250);
        sliderHeight.setMinimum(150);
        sliderHeight.setMinorTickSpacing(1);
        sliderHeight.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderHeightStateChanged(evt);
            }
        });

        tfDisplayHeight.setEditable(false);
        tfDisplayHeight.setText("150cm");

        jLabel5.setText("Height:");

        jLabel6.setText("Date of birth:");

        ftDateOfBirth.setText("yyyy/MM/dd");

        btVerifyAndAdd.setText("Verify and add below");
        btVerifyAndAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerifyAndAddActionPerformed(evt);
            }
        });

        taDisplayInfo.setColumns(20);
        taDisplayInfo.setRows(5);
        jScrollPane1.setViewportView(taDisplayInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lblName)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sliderHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDisplayHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbPetsFish)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPetsPig)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPetsGoat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPetsOther))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbGenderMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbGenderFemale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbGenderNotSure))
                            .addComponent(tfName)
                            .addComponent(tfPassportNo)
                            .addComponent(comboContinent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btVerifyAndAdd))
                            .addComponent(ftDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPassportNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbGenderMale)
                    .addComponent(rbGenderFemale)
                    .addComponent(rbGenderNotSure)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbPetsFish)
                    .addComponent(cbPetsPig)
                    .addComponent(cbPetsGoat)
                    .addComponent(cbPetsOther))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfDisplayHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVerifyAndAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVerifyAndAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerifyAndAddActionPerformed
    String name = tfName.getText();
    if(!name.matches("^[a-zA-Z- ]{1,50}$"))
    {
        JOptionPane.showMessageDialog(this, "Seriously? You don't know how to write your own fucking name? Try again", 
                "Are you kidding?", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    String passport = tfPassportNo.getText();
    if(!passport.matches("^[A-Z]{2}[0-9]{6}$"))
    {
        JOptionPane.showMessageDialog(this, "Take a look at your passport number, bro. It ain't right",
                "What's that?!", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if(comboContinent.getSelectedIndex() == 0)
    {
        JOptionPane.showMessageDialog(this, "You forgot to select a continent, nigga. What did you smoke?",
                "From what planet are you from?", JOptionPane.ERROR_MESSAGE);
        return;
    }
    String continent = comboContinent.getSelectedItem().toString();
    
    String gender = "";
    if(rbGenderMale.isSelected())
    {
        gender = "Male";
    }
    else if(rbGenderFemale.isSelected())
    {
        gender = "Female";
    }
    else if(rbGenderNotSure.isSelected())
    {
        gender = "Not sure";
    }
    else
    {
        JOptionPane.showMessageDialog(this, "You have to select a gender. If you're not sure if you're male or female, just pick 'Not sure'.", 
                "Missing information", JOptionPane.INFORMATION_MESSAGE);
    }
    
    ArrayList<String> petsList = new ArrayList<>();    
    if(cbPetsFish.isSelected())
    {
        petsList.add("Fish");
    }
    if(cbPetsPig.isSelected())
    {
        petsList.add("Pig"); 
    }
    if(cbPetsGoat.isSelected())
    {
        petsList.add("Goat"); 
    }
    if(cbPetsOther.isSelected())
    {
        petsList.add("Other"); 
    }
    String pets = String.join(", ",petsList);
    
    
    int height = sliderHeight.getValue();
    
    
    Date dateOfBirth = null;
    SimpleDateFormat correctFormat = new SimpleDateFormat("yyyy/MM/dd");
    
    try
    {
        dateOfBirth = correctFormat.parse(ftDateOfBirth.getText());
    }
    catch(ParseException ex)
    {
        JOptionPane.showMessageDialog(this, "This date is wrong, bro. Try again", "What?!", 
                JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    String info = String.format("Name: %s%nPassport Number: %s%nContinent of origin: %s%nGender: %s%nPets: %s%n"
            + "Height: %d%nDate of birth: %tF", name, passport, continent, gender, pets, height, dateOfBirth);
    taDisplayInfo.setText(info);
    
    
    }//GEN-LAST:event_btVerifyAndAddActionPerformed

    private void sliderHeightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderHeightStateChanged
        tfDisplayHeight.setText(sliderHeight.getValue() + "cm");
    }//GEN-LAST:event_sliderHeightStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practice3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practice3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practice3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practice3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practice3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVerifyAndAdd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbPetsFish;
    private javax.swing.JCheckBox cbPetsGoat;
    private javax.swing.JCheckBox cbPetsOther;
    private javax.swing.JCheckBox cbPetsPig;
    private javax.swing.JComboBox<String> comboContinent;
    private javax.swing.JFormattedTextField ftDateOfBirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JRadioButton rbGenderFemale;
    private javax.swing.JRadioButton rbGenderMale;
    private javax.swing.JRadioButton rbGenderNotSure;
    private javax.swing.JSlider sliderHeight;
    private javax.swing.JTextArea taDisplayInfo;
    private javax.swing.JTextField tfDisplayHeight;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPassportNo;
    // End of variables declaration//GEN-END:variables
}
